### ISSUE TITLE
babel 严格模式下 出错

### ISSUE THREAD

**Issue by whatwg6** [yanhaijing/fis-parser-template#2]
babel严格模式，提前__inline(*.tmpl)报错，改用你的方案出现点问题，不知道该如何解决

fis.match('**.tmpl', {
    parser: fis.plugin('template', {
        sTag: '<#',
        eTag: '#>',
        global: 'template'
    }),
    isJsLike: true,
    release : false
});

![image](https://cloud.githubusercontent.com/assets/18499153/22677247/3152a9bc-ed2c-11e6-98ef-07986ca0b895.png)
Uncaught TypeError: Cannot read property '__encodeHTML' of undefined

**Comment by yanhaijing** [comment]
需要在 inline之前，保证windows有template实例，在fis环境里 可以在inline之前require一下template
下面是一个实例：

https://github.com/yanhaijing/fis3-base/blob/master/modules/app/test.es 这是一个例子

https://github.com/yanhaijing/fis3-base/blob/master/modules/util/template/template.es 这是设置全局template的例子

**Comment by yanhaijing** [comment]
我现在考虑fis-conf 加一个参数叫做 express ，这个设置 是一个js表达式，能够返回 template的实例

**Comment by whatwg6** [comment]
按照你的方式已经解决，多谢了；

**Comment by yanhaijing** [comment]
不谢，感谢使用，感谢反馈，多提提宝贵意见
